[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"
[build.processing.html]
  pretty_urls = false

[functions]

  [functions.node_version]
  external_node_modules = [
    "node-mailjet"
  ]
